CREATE TABLE User (
  userId INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (userId)
)ENGINE=InnoDB;

CREATE TABLE Car (
  carId INT NOT NULL AUTO_INCREMENT,
  currentLocation VARCHAR(100),
  status VARCHAR(50),
  PRIMARY KEY (carId)
)ENGINE=InnoDB;

CREATE TABLE Booking (
  bookingId INT NOT NULL AUTO_INCREMENT,
  src VARCHAR(100),
  dest VARCHAR(100),
  status VARCHAR(50),
  userId INT,
  carId INT,
  PRIMARY KEY (bookingId)
)ENGINE=InnoDB;
